apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
          image: gaurawesome/backend-app:453b76c89c0c8be2b6f63c131f261654ac998d93
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
