apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
          image: gcr.io/fluid-stratum-296023/backend-app:73c0b26482682394ece7bea54bcde744e6a42310
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
