apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.yaml convert -o k8s-manifests
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
          image: BACKEND_IMAGE_PLACEHOLDER
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
