apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
  namespace: app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service: backend
