apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
          image: gaurawesome/backend-app:d4bca5cb0fb3191e4f2c8ae9539d3b0f4c8bc80f
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
