apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: app
  labels:
    service: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: local-path 