apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
          image: gaurawesome/frontend-app:0e08bec37534288adc83a75aeabd17bd4ca21b34
          name: frontend
          ports:
            - containerPort: 80
      restartPolicy: Always
