apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
data:
  nginx.conf: |
    worker_processes 1;

    events { 
        worker_connections 1024; 
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            server_name localhost;

            # Serve static files from /usr/share/nginx/html
            location /_next/static/ {
                alias /usr/share/nginx/html/_next/static/;
            }

            # Reverse proxy API requests to the backend service
            location /api/ {
                proxy_pass http://backend; # Change this to your backend service URL
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Forward all other requests to Next.js server
            location / {
                proxy_pass http://localhost:3000; # Next.js server running on port 3000
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }
