apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - image: gaurawesome/frontend-app:ba88c336626ed33ae8f49a4e23044ae8c74dacb2
          name: frontend
          ports:
            - containerPort: 80
      restartPolicy: Always
